### PR TITLE
Fix PEP8

### PR DESCRIPTION
**Pull request by cbrnr**
I've fixed all PEP8 complaints, hopefully without impacting anything else.

### CODE REVIEW

**Comment by agricolab** [comment]
Is there a consensus on which formatter to use for xdf-python, e.g. `autopep8`, `yapf` or `black` or is the formatting kept in shape manually?

**Comment by cbrnr** [comment]
I usually do it manually, but I'd be fine with using any of the tools you've mentioned (`black` seems to be the most popular choice at the moment).

**Comment by agricolab** [comment]
I read through it and could find no fault. Additionally, pytest runs fine on my machine, too.
Do you want to run an autoformatter first? I personally prefer black.

**Comment by cbrnr** [comment]
Alright, the code is now black auto-formatted (with `-l 79` which is PEP8-compliant, although I'm starting to think that something like 92 lines like in Julia might be a more sensible character limit, but let's not discuss this here and now). @agricolab if you're happy feel free to merge.

**Pull request merged**
