### PR TITLE
_jitter_removal Fix

### PR DESCRIPTION
**Pull request by ollie-d**
Modified '_jitter_removal' in order to match the MATLAB equivalent function

### CODE REVIEW

**Comment by cbrnr** [comment]
Could you please add an entry to `CHANGELOG.md` (in the "Fixed" section which you have to create)?

**Comment by ollie-d** [comment]
Sorry, I wasn't sure if I should make the entry myself. Please let me know if there's anything else I should do!

**Comment by cbrnr** [comment]
Thanks, I pushed a minor change (we don't need to mention that it now matches what the MATLAB implementation does, because all that counts is that the bug is now fixed).

I'll wait a bit to see if @tstenner or @cboulay have time to take a look, but if not I'd really like to merge this soon (and push a new release).

**Comment by cboulay** [comment]
I’m in transit now. I’ll take a look tomorrow.

**Comment by cboulay** [comment]
For #34

**Comment by cboulay** [comment]
I'm going to merge this in then make some additional changes. Briefly, I think the `np.hstack((0, indices + 1, indices, nsamples - 1))` line and the following reshaping line is a little bit hard to decipher with a quick scan. I'm going to be very explicit about creating a vector of range_starts and range_stops.

**Pull request merged**
