### PR TITLE
Support pathlib objects

### PR DESCRIPTION
**Pull request by cbrnr**
Fixes https://github.com/sccn/xdf/issues/41.

I've also managed to shave off one level of precious indentation space in case you're wondering why the change is so big.

### CODE REVIEW

**Comment by cboulay** [comment]
The original `with <open> as f:` is preferred because it automatically closes the file when the context is left, either naturally at the end of loading or if there's an exception. In the PR form there is no f.close() so the file remains open.

**Comment by cbrnr** [comment]
Of course I forgot the `close` 😄. I normally prefer the context manager too, but in this case I think it is better to explicitly call `open` and `close` because we really need that horizontal space.

**Comment by tstenner** [comment]
What if an exception occurs somewhere before the `close`?

I'm all for reducing the indentation level, but it's not related to the pathlib changes and it interferes with a lot of other PRs.

**Comment by cbrnr** [comment]
OK, I'll revert this, but we need to take care of exceptions anyway, because right now we catch all exceptions at the end. Technically, we could also add `f.close` to a `finally` block, but we can discuss this in a later PR.

**Comment by tstenner** [comment]
Looks good to me. If @cboulay doesn't have any objections we should squash and merge it.

**Comment by cboulay** [comment]
I merged a squashed version of this.

**Pull request closed without merging**
